id: IF7864BFF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T22:59:11+00:00'
last_modified: '2022-06-08T17:09:00.831461+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13837
  title: སྐོང་གསོ་དངོས་གྲུབ་རོལ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D1CC:
      image_group_id: I1KG16125
      title: ''
      total_pages: 182
      order: 1
      base_file: D1CC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
